name: 主流板塊排行榜推播

on:
  schedule:
    # 每小時整點執行（UTC 時間）
    - cron: '0 * * * *'
  workflow_dispatch:

# 防止並發執行
concurrency:
  group: sector-ranking
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run sector ranking task
        env:
          CG_GECKO_API_KEY: ${{ secrets.CG_GECKO_API_KEY }}
          CG_API_KEY: ${{ secrets.CG_API_KEY }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TG_THREAD_IDS: ${{ secrets.TG_THREAD_IDS }}
          TG_THREAD_SECTOR_RANKING: ${{ secrets.TG_THREAD_SECTOR_RANKING }}
        run: |
          timeout 480 python jackbot.py sector_ranking || exit 0
          echo "任務執行完成"

