name: 巨鯨持倉動向

on:
  schedule:
    # 每 8 小時執行一次（UTC 時間：00:00, 08:00, 16:00）
    - cron: '0 */8 * * *'
  workflow_dispatch:

# 防止並發執行
concurrency:
  group: whale-position
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      actions: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run whale position task
        env:
          CG_API_KEY: ${{ secrets.CG_API_KEY }}
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          TG_THREAD_IDS: ${{ secrets.TG_THREAD_IDS }}
          TG_THREAD_WHALE_POSITION: ${{ secrets.TG_THREAD_WHALE_POSITION }}
        run: |
          timeout 480 python jackbot.py whale_position || exit 0
          echo "任務執行完成"

